export const CATEGORYLIST_FETCH_START = "CATEGORYLIST_FETCH_START";
export const CATEGORYLIST_FETCH_SUCCESS = "CATEGORYLIST_FETCH_SUCCESS";
export const CATEGORYLIST_FETCH_ERROR = "CATEGORYLIST_FETCH_ERROR";

export const CATEGORY_FETCH_START = "CATEGORY_FETCH_START";
export const CATEGORY_FETCH_SUCCESS = "CATEGORY_FETCH_SUCCESS";
export const CATEGORY_FETCH_FAIL = "CATEGORY_FETCH_FAIL";

export const DELETE_CATEGORY_START = "DELETE_CATEGORY_START";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL";
export const DELETE_CATEGORY_RESET = "DELETE_CATEGORY_RESET";

export const CREATE_CATEGORY_START = "CREATE_CATEGORY_START";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAIL = "CREATE_CATEGORY_FAIL";
export const CREATE_CATEGORY_RESET = "CREATE_CATEGORY_RESET";

export const EDIT_CATEGORY_START = "EDIT_CATEGORY_START";
export const EDIT_CATEGORY_SUCCESS = "EDIT_CATEGORY_SUCCESS";
export const EDIT_CATEGORY_FAIL = "EDIT_CATEGORY_FAIL";
export const EDIT_CATEGORY_RESET = "EDIT_CATEGORY_RESET";